title: Azra Ismail
logo: /assets/img/profile.jpeg
description: (she, her, hers)
Assistant Professor
Department of Biomedical Informatics
Hubert Department of Global Health
Emory University, Atlanta, GA

azra.ismail AT emory.edu

show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
